export const IMAGE_TOOLS = [
  { name: 'get_image_info', description: 'Get image metadata: dimensions, format, size, color space.', inputSchema: { type: 'object', properties: { path: { type: 'string', description: 'Storage path to the image file' } }, required: ['path'] } },
  { name: 'resize_image', description: 'Resize an image with aspect ratio preservation.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, width: { type: 'number' }, height: { type: 'number' }, fit: { type: 'string', enum: ['cover', 'contain', 'fill', 'inside', 'outside'] }, output_path: { type: 'string' } }, required: ['path'] } },
  { name: 'crop_image', description: 'Crop a rectangular region from an image.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, left: { type: 'number' }, top: { type: 'number' }, width: { type: 'number' }, height: { type: 'number' }, output_path: { type: 'string' } }, required: ['path', 'left', 'top', 'width', 'height'] } },
  { name: 'rotate_image', description: 'Rotate an image by a given angle.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, angle: { type: 'number', description: 'Rotation angle in degrees' }, output_path: { type: 'string' } }, required: ['path', 'angle'] } },
  { name: 'flip_image', description: 'Flip an image horizontally or vertically.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, direction: { type: 'string', enum: ['horizontal', 'vertical'] }, output_path: { type: 'string' } }, required: ['path', 'direction'] } },
  { name: 'grayscale_image', description: 'Convert an image to grayscale.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, output_path: { type: 'string' } }, required: ['path'] } },
  { name: 'blur_image', description: 'Apply Gaussian blur to an image.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, sigma: { type: 'number', description: 'Blur radius (default: 3)' }, output_path: { type: 'string' } }, required: ['path'] } },
  { name: 'adjust_image', description: 'Adjust image brightness and saturation.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, brightness: { type: 'number' }, saturation: { type: 'number' }, output_path: { type: 'string' } }, required: ['path'] } },
  { name: 'compress_image', description: 'Compress an image to reduce file size.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, quality: { type: 'number', description: 'Quality 1-100 (default: 80)' }, output_path: { type: 'string' } }, required: ['path'] } },
  { name: 'convert_format', description: 'Convert image to another format (jpeg, png, webp, avif, tiff).', inputSchema: { type: 'object', properties: { path: { type: 'string' }, format: { type: 'string', enum: ['jpeg', 'png', 'webp', 'avif', 'tiff'] }, quality: { type: 'number' }, output_path: { type: 'string' } }, required: ['path', 'format'] } },
  { name: 'add_border', description: 'Add a colored border around an image.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, width: { type: 'number', description: 'Border width in pixels' }, color: { type: 'string', description: 'Border color (hex or named)' }, output_path: { type: 'string' } }, required: ['path', 'width'] } },
  { name: 'pixelate_image', description: 'Apply pixelation effect to an image.', inputSchema: { type: 'object', properties: { path: { type: 'string' }, pixel_size: { type: 'number', description: 'Pixel block size (default: 10)' }, output_path: { type: 'string' } }, required: ['path'] } },
];
